name: Linux packages

on: [push, pull_request]

env:
  PACKAGE_NAME: d3s-nagios-plugins-git
  PACKAGE_MAINTAINER: vhotspur
  PACKAGE_SUMMARY: "Collection of various Nagios plugins"
  PACKAGE_VERSION: 1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Prepare install for Debian
        run: |
          pip install --root ${{github.workspace}}/pkg-deb --prefix /usr .
          find ${{github.workspace}}/pkg-deb

      - uses: jiro4989/build-deb-action@v3
        with:
          package_root: ${{github.workspace}}/pkg-deb
          package: ${{ env.PACKAGE_NAME }}
          maintainer: ${{ env.PACKAGE_MAINTAINER }}
          desc: '${{ env.PACKAGE_SUMMARY }}'
          version: '${{ env.PACKAGE_VERSION }}'
          arch: 'amd64'

      - uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: |
            ./d3s*.deb
