name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  PACKAGE_NAME: d3s-nagios-plugins
  PACKAGE_MAINTAINER: vhotspur
  PACKAGE_SUMMARY: "Collection of various Nagios plugins"
  PACKAGE_VERSION: 1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Prepare install for Debian
        run: |
          pip install --root ${{github.workspace}}/pkg-deb --prefix /usr .
          find ${{github.workspace}}/pkg-deb

      - uses: jiro4989/build-deb-action@v3
        with:
          package_root: ${{github.workspace}}/pkg-deb
          package: ${{ env.PACKAGE_NAME }}
          maintainer: ${{ env.PACKAGE_MAINTAINER }}
          desc: '${{ env.PACKAGE_SUMMARY }}'
          version: '${{ env.PACKAGE_VERSION }}'
          arch: 'amd64'

      - name: Setup release notes
        run: ./contrib/get-release-notes.sh ${{ env.PACKAGE_VERSION }} >gh-release-body.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: gh-release-body.txt
          files: |
            d3s*.deb
